name: Release by avkiller

on:
  push:
    tags:
      - "v[0-9]*"
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'release tags(Default: v0.4.15)'
        required: true
        default: 'v0.4.15'

jobs:
  prepare-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Build UI
        run: |
          npm --prefix=./ui ci
          npm --prefix=./ui run build

      - name: Upload UI build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: ui-build
          path: ./ui/dist
          retention-days: 1

  build-linux:
    needs: prepare-ui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Download UI build artifacts
        uses: actions/download-artifact@v6
        with:
          name: ui-build
          path: ./ui/dist

      - name: Build Linux binaries
        env:
          CGO_ENABLED: 0
          GOOS: linux
          VERSION: ${{ inputs.version }}
        run: |
          mkdir -p dist/linux
          if [ "$GITHUB_EVENT_NAME" != "workflow_dispatch" ]; then
            # 使用当前的tags
            VERSION = "GITHUB_REF#refs/tags/"
          fi
          for ARCH in amd64 arm64; do
            if [ "$ARCH" == "armv7" ]; then
              go env -w GOARCH=arm
              go env -w GOARM=7
            else
              go env -w GOARCH=$ARCH
              go env -u GOARM
            fi
            
            go build -trimpath -ldflags="-s -w" -o dist/linux/certimate_${VERSION}_linux_$ARCH
          done

      - name: Upload Linux binaries
        uses: actions/upload-artifact@v5
        with:
          name: linux-binaries
          path: dist/linux/
          retention-days: 1

  build-macos:
    needs: prepare-ui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Download UI build artifacts
        uses: actions/download-artifact@v6
        with:
          name: ui-build
          path: ./ui/dist

      - name: Build macOS binaries
        env:
          CGO_ENABLED: 0
          GOOS: darwin
          VERSION: ${{ inputs.version }}
        run: |
          mkdir -p dist/darwin
          if [ "$GITHUB_EVENT_NAME" != "workflow_dispatch" ]; then
            # 使用当前的tags
            VERSION = "GITHUB_REF#refs/tags/"
          fi
          for ARCH in amd64 arm64; do
            go env -w GOARCH=$ARCH
            go build -trimpath -ldflags="-s -w" -o dist/darwin/certimate_${VERSION}_darwin_$ARCH
          done

      - name: Upload macOS binaries
        uses: actions/upload-artifact@v5
        with:
          name: macos-binaries
          path: dist/darwin/
          retention-days: 1

  build-windows:
    needs: prepare-ui
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Download UI build artifacts
        uses: actions/download-artifact@v6
        with:
          name: ui-build
          path: ./ui/dist

      - name: Build Windows binaries
        env:
          CGO_ENABLED: 0
          GOOS: windows
          VERSION: ${{ inputs.version }}
        run: |
          mkdir -p dist/windows
          if [ "$GITHUB_EVENT_NAME" != "workflow_dispatch" ]; then
            # 使用当前的tags
            VERSION = "GITHUB_REF#refs/tags/"
          fi
          for ARCH in amd64 arm64; do
            go env -w GOARCH=$ARCH
            go build -trimpath -ldflags="-s -w" -o dist/windows/certimate_${VERSION}_windows_$ARCH.exe
          done

      - name: Upload Windows binaries
        uses: actions/upload-artifact@v5
        with:
          name: windows-binaries
          path: dist/windows/
          retention-days: 1

  create-release:
    needs: [build-linux, build-macos, build-windows]
    runs-on: ubuntu-latest
    env:
          VERSION: ${{ inputs.version }}
          TAG_NAME: ${{ inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download all binaries
        uses: actions/download-artifact@v6
        with:
          path: ./artifacts

      - name: Prepare release assets
        run: |
          mkdir -p dist
          cp -r artifacts/linux-binaries/* dist/
          cp -r artifacts/macos-binaries/* dist/
          cp -r artifacts/windows-binaries/* dist/

          find dist -type f -not -name "*.exe" -exec chmod +x {} \;

          cd dist
          for bin in certimate_*; do
            if [[ "$bin" == *".exe" ]]; then
              entrypoint="certimate.exe"
            else
              entrypoint="certimate"
            fi

            tmpdir=$(mktemp -d)
            cp "$bin" "${tmpdir}/${entrypoint}"
            cp ../LICENSE "$tmpdir/LICENSE"
            cp ../README.md "$tmpdir/README.md"
            cp ../CHANGELOG.md "$tmpdir/CHANGELOG.md"

            if [[ "$bin" == *".exe" ]]; then
              zip -j "${bin%.exe}.zip" "$tmpdir"/*
            else
              zip -j -X "${bin}.zip" "$tmpdir"/*
            fi

            rm -rf "$tmpdir"
          done

          sha256sum *.zip > checksums.txt   
          
      - name: get tag
        
        run: |
          if [ "$GITHUB_EVENT_NAME" != "workflow_dispatch" ]; then
            # 使用当前的tags
            tag="${GITHUB_REF#refs/tags/}"
          fi
          echo "TAG_NAME=$tag" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            dist/*.zip
            dist/checksums.txt
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
